version: '3'
services:
  api:
    image: movies-backend
    build: packages/backend/.
    environment:
      - MOVIEREVIEWS_DB_URI=mongodb://db:27017/?retryWrites=true&w=majority
      - MOVIEREVIEWS_NS=movies-database
      - PORT=3000
    entrypoint:
      - npm
      - run
      - dev
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend/:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data to a named volume

networks:
  backend:
    driver: bridge
volumes:
  mongodb_data: